sudo: required

services:
  - docker

language: python

cache:
  directories:
    - "$HOME/google-cloud-sdk/"


env:
  # Make sure gcloud command is on our PATH
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin

before_install:
  - openssl aes-256-cbc -K $encrypted_f842bcbfc33d_key -iv $encrypted_f842bcbfc33d_iv
    -in all_keys.tar.gz.enc -out all_keys.tar.gz -d

  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
      curl https://sdk.cloud.google.com | bash;
    fi

  - tar -xzf all_keys.tar.gz

  - gcloud auth activate-service-account --key-file all_keys/peerChat-gcp-service-account-key.json

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - cp -r all_keys/api-private api/private

  - cp -r all_keys/app-private app/private

  - docker build -t swrdfish/mode:latest . 

script:
  - docker push swrdfish/mode:latest


