apiVersion: v1
kind: Pod
metadata:
  name: mode
spec:
  containers:
    - name: mode
      image: docker.io/swrdfish/mode:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 80
          hostPort: 80